var language_of_Pakistan = 'urdu';
console.log("Is language of Pakistan == 'urdu'? I predict True.");
console.log(language_of_Pakistan == 'urdu');
var capital_Pakistan = 'Islamabad';
console.log("Is capital of Pakistan == 'Karachi'? I predict False.");
console.log(capital_Pakistan == 'Karachi');
var myFavNum = 3;
console.log("Is my Favourite number == 3? I predict True.");
console.log(myFavNum == 3);
var my_car = 'Alto';
console.log("Is my car name == 'Lamborghini'? I predict True.");
console.log(my_car == 'Lamborghini');
var my_qualification = 'MS';
console.log("Is my max qualification == 'MS'? I predict True.");
console.log(my_qualification == 'MS');
var my_Fav_City = 'Islamabad';
console.log("Is my Favourite City == 'Paris'? I predict False.");
console.log(my_Fav_City == 'Paris');
var country_Ind_Day = '14 Aug 1947';
console.log("Is my country independence day == '14 Aug, 1947'? I predict True.");
console.log(country_Ind_Day == '14 Aug, 1947');
var motivationLevel = 'High';
console.log("Is my motivationLevel == 'High'? I predict True.");
console.log(motivationLevel == 'High');
var no_of_brothers = 2;
console.log("Is number of my brothers == 2? I predict True.");
console.log(no_of_brothers == 2);
var mother_tongue = 'Urdu';
console.log("Is my mother tongue == 'English'? I predict False.");
console.log(mother_tongue == 'English');
